import "@/styles/app.scss";

export const metadata = {
  title: 'Next.js Guest Layout',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
